worker:
  service:
    name: worker
    port: 4000
    type: ClusterIP
  selector: worker-app
  replicaCount: 2
  image:
    repository: mokchhedul/worker_service
    tagBlue: v1
    tagGreen: v2
    pullPolicy: IfNotPresent
  activeVersion: blue   
