vote:
  password: password123
  service:
    name: vote
    type: ClusterIP
    port: 80
  selector: vote
  replicaCount: 2
  image:
    repository: mokchhedul/vote_service
    tag: latest
    pullPolicy: IfNotPresent
